# Generated by Django 4.1.4 on 2023-04-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_coursecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baxtli_mojozlar', models.CharField(max_length=20)),
                ('loyihalar', models.CharField(max_length=20)),
                ('qollab_quvvatlash', models.CharField(max_length=20)),
                ('mexnatkashlar', models.CharField(max_length=20)),
            ],
        ),
    ]
