# Generated by Django 4.1.4 on 2023-04-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_statistic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='baxtli_mojozlar',
            new_name='baxtli_mijozlar',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='mexnatkashlar',
            new_name='mehnatkashlar',
        ),
    ]
