# Generated by Django 4.1.4 on 2023-04-14 17:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_baxtli_mojozlar_statistic_baxtli_mijozlar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asosiy_Malumotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='Asosiy_Malumotlar')),
            ],
        ),
    ]
